import Foundation

extension AppStrings {
    static let translationsDebtsList: [String: [String: String]] = [
        "debts.empty.title": [
            "en": "No Debts Yet",
            "es": "Sin Deudas A\u{00FA}n",
            "fr": "Aucune Dette",
            "pt": "Sem D\u{00ED}vidas",
            "ja": "\u{50B5}\u{52D9}\u{306F}\u{3042}\u{308A}\u{307E}\u{305B}\u{3093}",
            "ko": "\u{BE5A}\u{C774} \u{C5C6}\u{C2B5}\u{B2C8}\u{B2E4}",
        ],
        "debts.empty.subtitle": [
            "en": "Start tracking your debts by tapping the + button below.",
            "es": "Empieza a rastrear tus deudas tocando el bot\u{00F3}n + abajo.",
            "fr": "Commencez \u{00E0} suivre vos dettes en appuyant sur le bouton +.",
            "pt": "Comece a rastrear suas d\u{00ED}vidas tocando no bot\u{00E3}o + abaixo.",
            "ja": "\u{4E0B}\u{306E}+\u{30DC}\u{30BF}\u{30F3}\u{3092}\u{30BF}\u{30C3}\u{30D7}\u{3057}\u{3066}\u{50B5}\u{52D9}\u{306E}\u{8FFD}\u{8DE1}\u{3092}\u{958B}\u{59CB}\u{3057}\u{307E}\u{3057}\u{3087}\u{3046}\u{3002}",
            "ko": "\u{C544}\u{B798} + \u{BC84}\u{D2BC}\u{C744} \u{D0ED}\u{D558}\u{C5EC} \u{BE5A} \u{CD94}\u{C801}\u{C744} \u{C2DC}\u{C791}\u{D558}\u{C138}\u{C694}.",
        ],
        "debts.noResults.title": [
            "en": "No Results",
            "es": "Sin Resultados",
            "fr": "Aucun R\u{00E9}sultat",
            "pt": "Sem Resultados",
            "ja": "\u{7D50}\u{679C}\u{306A}\u{3057}",
            "ko": "\u{ACB0}\u{ACFC} \u{C5C6}\u{C74C}",
        ],
        "debts.noResults.subtitle": [
            "en": "Try adjusting your filters or search.",
            "es": "Intenta ajustar tus filtros o b\u{00FA}squeda.",
            "fr": "Essayez d'ajuster vos filtres ou recherche.",
            "pt": "Tente ajustar seus filtros ou busca.",
            "ja": "\u{30D5}\u{30A3}\u{30EB}\u{30BF}\u{30FC}\u{3084}\u{691C}\u{7D22}\u{3092}\u{8ABF}\u{6574}\u{3057}\u{3066}\u{304F}\u{3060}\u{3055}\u{3044}\u{3002}",
            "ko": "\u{D544}\u{D130}\u{B098} \u{AC80}\u{C0C9}\u{C744} \u{C870}\u{C815}\u{D574} \u{BCF4}\u{C138}\u{C694}.",
        ],
        "debts.searchPrompt": [
            "en": "Search debts...",
            "es": "Buscar deudas...",
            "fr": "Rechercher des dettes...",
            "pt": "Buscar d\u{00ED}vidas...",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{691C}\u{7D22}...",
            "ko": "\u{BE5A} \u{AC80}\u{C0C9}...",
        ],
        "filter.all": [
            "en": "All",
            "es": "Todos",
            "fr": "Tout",
            "pt": "Todos",
            "ja": "\u{3059}\u{3079}\u{3066}",
            "ko": "\u{C804}\u{CCB4}",
        ],
        "filter.owedToMe": [
            "en": "Owed to Me",
            "es": "Me Deben",
            "fr": "On Me Doit",
            "pt": "Me Devem",
            "ja": "\u{8CB8}\u{3057}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{BC1B}\u{C744} \u{B3C8}",
        ],
        "filter.iOwe": [
            "en": "I Owe",
            "es": "Yo Debo",
            "fr": "Je Dois",
            "pt": "Eu Devo",
            "ja": "\u{501F}\u{308A}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{AC1A}\u{C740} \u{B3C8}",
        ],
        "filter.incoming": [
            "en": "Incoming",
            "es": "Entrante",
            "fr": "Entrant",
            "pt": "Entrada",
            "ja": "\u{5165}\u{91D1}",
            "ko": "\u{C218}\u{C785}",
        ],
        "filter.outgoing": [
            "en": "Outgoing",
            "es": "Saliente",
            "fr": "Sortant",
            "pt": "Sa\u{00ED}da",
            "ja": "\u{51FA}\u{91D1}",
            "ko": "\u{C9C0}\u{CD9C}",
        ],
        "sort.dateCreated": [
            "en": "Date Created",
            "es": "Fecha de Creaci\u{00F3}n",
            "fr": "Date de Cr\u{00E9}ation",
            "pt": "Data de Cria\u{00E7}\u{00E3}o",
            "ja": "\u{4F5C}\u{6210}\u{65E5}",
            "ko": "\u{C0DD}\u{C131}\u{C77C}",
        ],
        "sort.dueDate": [
            "en": "Due Date",
            "es": "Fecha de Vencimiento",
            "fr": "Date d'\u{00E9}ch\u{00E9}ance",
            "pt": "Data de Vencimento",
            "ja": "\u{671F}\u{9650}\u{65E5}",
            "ko": "\u{B9CC}\u{AE30}\u{C77C}",
        ],
        "sort.amount": [
            "en": "Amount",
            "es": "Monto",
            "fr": "Montant",
            "pt": "Valor",
            "ja": "\u{91D1}\u{984D}",
            "ko": "\u{AE08}\u{C561}",
        ],
        "sort.person": [
            "en": "Person",
            "es": "Persona",
            "fr": "Personne",
            "pt": "Pessoa",
            "ja": "\u{4EBA}\u{7269}",
            "ko": "\u{C0AC}\u{B78C}",
        ],
    ]
}
