import Foundation

extension AppStrings {
    static let translationsDebtLabels: [String: [String: String]] = [
        "status.active": [
            "en": "Active",
            "es": "Activa",
            "fr": "Active",
            "pt": "Ativa",
            "ja": "\u{30A2}\u{30AF}\u{30C6}\u{30A3}\u{30D6}",
            "ko": "\u{D65C}\u{C131}",
        ],
        "status.partiallyPaid": [
            "en": "Partially Paid",
            "es": "Parcialmente Pagada",
            "fr": "Partiellement Pay\u{00E9}",
            "pt": "Parcialmente Paga",
            "ja": "\u{90E8}\u{5206}\u{652F}\u{6255}\u{3044}\u{6E08}",
            "ko": "\u{BD80}\u{BD84} \u{C0C1}\u{D658}",
        ],
        "status.paidOff": [
            "en": "Paid Off",
            "es": "Pagada",
            "fr": "Rembours\u{00E9}",
            "pt": "Paga",
            "ja": "\u{5B8C}\u{6E08}",
            "ko": "\u{C644}\u{B0A9}",
        ],
        "status.overdue": [
            "en": "Overdue",
            "es": "Vencida",
            "fr": "En Retard",
            "pt": "Atrasada",
            "ja": "\u{671F}\u{9650}\u{5207}\u{308C}",
            "ko": "\u{C5F0}\u{CCB4}",
        ],
        "status.forgiven": [
            "en": "Forgiven",
            "es": "Perdonada",
            "fr": "Pardonn\u{00E9}",
            "pt": "Perdoada",
            "ja": "\u{514D}\u{9664}",
            "ko": "\u{D0D5}\u{AC10}",
        ],
        "status.overdueBadge": [
            "en": "OVERDUE",
            "es": "VENCIDA",
            "fr": "EN RETARD",
            "pt": "ATRASADA",
            "ja": "\u{671F}\u{9650}\u{5207}\u{308C}",
            "ko": "\u{C5F0}\u{CCB4}",
        ],
        "status.paid": [
            "en": "Paid",
            "es": "Pagada",
            "fr": "Pay\u{00E9}",
            "pt": "Paga",
            "ja": "\u{652F}\u{6255}\u{6E08}",
            "ko": "\u{C644}\u{B0A9}",
        ],
        "direction.owedToMe": [
            "en": "Owed to Me",
            "es": "Me Deben",
            "fr": "On Me Doit",
            "pt": "Me Devem",
            "ja": "\u{8CB8}\u{3057}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{BC1B}\u{C744} \u{B3C8}",
        ],
        "direction.iOwe": [
            "en": "I Owe",
            "es": "Yo Debo",
            "fr": "Je Dois",
            "pt": "Eu Devo",
            "ja": "\u{501F}\u{308A}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{AC1A}\u{C740} \u{B3C8}",
        ],
        "direction.incoming": [
            "en": "Incoming",
            "es": "Entrante",
            "fr": "Entrant",
            "pt": "Entrada",
            "ja": "\u{5165}\u{91D1}",
            "ko": "\u{C218}\u{C785}",
        ],
        "direction.outgoing": [
            "en": "Outgoing",
            "es": "Saliente",
            "fr": "Sortant",
            "pt": "Sa\u{00ED}da",
            "ja": "\u{51FA}\u{91D1}",
            "ko": "\u{C9C0}\u{CD9C}",
        ],
        "direction.someoneOwesMe": [
            "en": "Someone owes me",
            "es": "Alguien me debe",
            "fr": "Quelqu'un me doit",
            "pt": "Algu\u{00E9}m me deve",
            "ja": "\u{8AB0}\u{304B}\u{304C}\u{79C1}\u{306B}\u{501F}\u{308A}\u{3066}\u{3044}\u{308B}",
            "ko": "\u{B204}\u{AD70}\u{AC00} \u{B098}\u{C5D0}\u{AC8C} \u{BE5A}\u{C84C}\u{B2E4}",
        ],
        "direction.iOweSomeone": [
            "en": "I owe someone",
            "es": "Yo le debo a alguien",
            "fr": "Je dois \u{00E0} quelqu'un",
            "pt": "Eu devo a algu\u{00E9}m",
            "ja": "\u{79C1}\u{304C}\u{8AB0}\u{304B}\u{306B}\u{501F}\u{308A}\u{3066}\u{3044}\u{308B}",
            "ko": "\u{B0B4}\u{AC00} \u{B204}\u{AD70}\u{AC00}\u{C5D0}\u{AC8C} \u{BE5A}\u{C84C}\u{B2E4}",
        ],
        "debts.addDebt": [
            "en": "Add Debt",
            "es": "A\u{00F1}adir Deuda",
            "fr": "Ajouter une Dette",
            "pt": "Adicionar D\u{00ED}vida",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{8FFD}\u{52A0}",
            "ko": "\u{BE5A} \u{CD94}\u{AC00}",
        ],
        "debts.sort": [
            "en": "Sort",
            "es": "Ordenar",
            "fr": "Trier",
            "pt": "Ordenar",
            "ja": "\u{4E26}\u{3079}\u{66FF}\u{3048}",
            "ko": "\u{C815}\u{B82C}",
        ],
        "a11y.debt.row": [
            "en": "%@ \u{2014} %@, %@",
            "es": "%@ \u{2014} %@, %@",
            "fr": "%@ \u{2014} %@, %@",
            "pt": "%@ \u{2014} %@, %@",
            "ja": "%@ \u{2014} %@\u{3001}%@",
            "ko": "%@ \u{2014} %@, %@",
        ],
        "a11y.debt.row.hint": [
            "en": "Double-tap to view details",
            "es": "Toca dos veces para ver detalles",
            "fr": "Touchez deux fois pour voir les d\u{00E9}tails",
            "pt": "Toque duas vezes para ver detalhes",
            "ja": "\u{30C0}\u{30D6}\u{30EB}\u{30BF}\u{30C3}\u{30D7}\u{3057}\u{3066}\u{8A73}\u{7D30}\u{3092}\u{8868}\u{793A}",
            "ko": "\u{C138}\u{BD80}\u{C815}\u{BCF4}\u{B97C} \u{BCF4}\u{B824}\u{BA74} \u{B450}\u{BC88} \u{D0ED}\u{D558}\u{C138}\u{C694}",
        ],
        "a11y.payment.row": [
            "en": "Payment of %@ to %@, %@",
            "es": "Pago de %@ a %@, %@",
            "fr": "Paiement de %@ \u{00E0} %@, %@",
            "pt": "Pagamento de %@ para %@, %@",
            "ja": "%@\u{3078}\u{306E}%@\u{306E}\u{652F}\u{6255}\u{3044}\u{3001}%@",
            "ko": "%@\u{C5D0}\u{AC8C} %@ \u{C9C0}\u{BD88}, %@",
        ],
    ]
}
