import Foundation

extension AppStrings {
    static let translationsProfile: [String: [String: String]] = [
        "profile.title": [
            "en": "Profile",
            "es": "Perfil",
            "fr": "Profil",
            "pt": "Perfil",
            "ja": "\u{30D7}\u{30ED}\u{30D5}\u{30A3}\u{30FC}\u{30EB}",
            "ko": "\u{D504}\u{B85C}\u{D544}",
        ],
        "profile.name": [
            "en": "Name",
            "es": "Nombre",
            "fr": "Nom",
            "pt": "Nome",
            "ja": "\u{540D}\u{524D}",
            "ko": "\u{C774}\u{B984}",
        ],
        "profile.namePlaceholder": [
            "en": "Your name",
            "es": "Tu nombre",
            "fr": "Votre nom",
            "pt": "Seu nome",
            "ja": "\u{3042}\u{306A}\u{305F}\u{306E}\u{540D}\u{524D}",
            "ko": "\u{C774}\u{B984}\u{C744} \u{C785}\u{B825}\u{D558}\u{C138}\u{C694}",
        ],
        "profile.language": [
            "en": "Language",
            "es": "Idioma",
            "fr": "Langue",
            "pt": "Idioma",
            "ja": "\u{8A00}\u{8A9E}",
            "ko": "\u{C5B8}\u{C5B4}",
        ],
        "profile.currency": [
            "en": "Currency",
            "es": "Moneda",
            "fr": "Devise",
            "pt": "Moeda",
            "ja": "\u{901A}\u{8CA8}",
            "ko": "\u{D1B5}\u{D654}",
        ],
        "profile.removePhoto": [
            "en": "Remove Photo",
            "es": "Eliminar Foto",
            "fr": "Supprimer la Photo",
            "pt": "Remover Foto",
            "ja": "\u{5199}\u{771F}\u{3092}\u{524A}\u{9664}",
            "ko": "\u{C0AC}\u{C9C4} \u{C0AD}\u{C81C}",
        ],
        "notifications.title": [
            "en": "Notifications",
            "es": "Notificaciones",
            "fr": "Notifications",
            "pt": "Notifica\u{00E7}\u{00F5}es",
            "ja": "\u{901A}\u{77E5}",
            "ko": "\u{C54C}\u{B9BC}",
        ],
        "notifications.enable": [
            "en": "Enable Notifications",
            "es": "Activar Notificaciones",
            "fr": "Activer les Notifications",
            "pt": "Ativar Notifica\u{00E7}\u{00F5}es",
            "ja": "\u{901A}\u{77E5}\u{3092}\u{6709}\u{52B9}\u{306B}\u{3059}\u{308B}",
            "ko": "\u{C54C}\u{B9BC} \u{D65C}\u{C131}\u{D654}",
        ],
        "notifications.description": [
            "en": "Receive reminders for upcoming debt due dates.",
            "es": "Recibe recordatorios para las fechas de vencimiento.",
            "fr": "Recevez des rappels pour les \u{00E9}ch\u{00E9}ances de dettes.",
            "pt": "Receba lembretes para as datas de vencimento.",
            "ja": "\u{50B5}\u{52D9}\u{306E}\u{671F}\u{9650}\u{306E}\u{30EA}\u{30DE}\u{30A4}\u{30F3}\u{30C0}\u{30FC}\u{3092}\u{53D7}\u{3051}\u{53D6}\u{308A}\u{307E}\u{3059}\u{3002}",
            "ko": "\u{BE5A} \u{B9CC}\u{AE30}\u{C77C} \u{C54C}\u{B9BC}\u{C744} \u{BC1B}\u{C2B5}\u{B2C8}\u{B2E4}.",
        ],
        "notifications.sectionHeader": [
            "en": "Notifications",
            "es": "Notificaciones",
            "fr": "Notifications",
            "pt": "Notifica\u{00E7}\u{00F5}es",
            "ja": "\u{901A}\u{77E5}",
            "ko": "\u{C54C}\u{B9BC}",
        ],
        "notifications.howItWorks": [
            "en": "How it works",
            "es": "C\u{00F3}mo funciona",
            "fr": "Comment \u{00E7}a marche",
            "pt": "Como funciona",
            "ja": "\u{4ED5}\u{7D44}\u{307F}",
            "ko": "\u{C791}\u{B3D9} \u{BC29}\u{C2DD}",
        ],
        "notifications.howItWorksDescription": [
            "en": "When you enable reminders on a debt, you'll receive a local notification at your chosen time. No data is sent to any server \u{2014} all notifications are processed on-device.",
            "es": "Cuando activas recordatorios en una deuda, recibir\u{00E1}s una notificaci\u{00F3}n local a la hora elegida. No se env\u{00ED}an datos a ning\u{00FA}n servidor.",
            "fr": "Lorsque vous activez les rappels sur une dette, vous recevrez une notification locale \u{00E0} l'heure choisie. Aucune donn\u{00E9}e n'est envoy\u{00E9}e \u{00E0} un serveur.",
            "pt": "Quando voc\u{00EA} ativa lembretes em uma d\u{00ED}vida, receber\u{00E1} uma notifica\u{00E7}\u{00E3}o local no hor\u{00E1}rio escolhido. Nenhum dado \u{00E9} enviado a servidores.",
            "ja": "\u{50B5}\u{52D9}\u{306E}\u{30EA}\u{30DE}\u{30A4}\u{30F3}\u{30C0}\u{30FC}\u{3092}\u{6709}\u{52B9}\u{306B}\u{3059}\u{308B}\u{3068}\u{3001}\u{6307}\u{5B9A}\u{3057}\u{305F}\u{6642}\u{523B}\u{306B}\u{30ED}\u{30FC}\u{30AB}\u{30EB}\u{901A}\u{77E5}\u{304C}\u{5C4A}\u{304D}\u{307E}\u{3059}\u{3002}\u{30C7}\u{30FC}\u{30BF}\u{306F}\u{30B5}\u{30FC}\u{30D0}\u{30FC}\u{306B}\u{9001}\u{4FE1}\u{3055}\u{308C}\u{307E}\u{305B}\u{3093}\u{3002}",
            "ko": "\u{BE5A}\u{C5D0} \u{C54C}\u{B9BC}\u{C744} \u{D65C}\u{C131}\u{D654}\u{D558}\u{BA74} \u{C120}\u{D0DD}\u{D55C} \u{C2DC}\u{AC04}\u{C5D0} \u{B85C}\u{CEEC} \u{C54C}\u{B9BC}\u{C744} \u{BC1B}\u{C2B5}\u{B2C8}\u{B2E4}. \u{C11C}\u{BC84}\u{B85C} \u{B370}\u{C774}\u{D130}\u{AC00} \u{C804}\u{C1A1}\u{B418}\u{C9C0} \u{C54A}\u{C2B5}\u{B2C8}\u{B2E4}.",
        ],
        "notifications.infoHeader": [
            "en": "Info",
            "es": "Informaci\u{00F3}n",
            "fr": "Info",
            "pt": "Informa\u{00E7}\u{00E3}o",
            "ja": "\u{60C5}\u{5831}",
            "ko": "\u{C815}\u{BCF4}",
        ],
        "biometric.faceId": [
            "en": "Face ID",
            "es": "Face ID",
            "fr": "Face ID",
            "pt": "Face ID",
            "ja": "Face ID",
            "ko": "Face ID",
        ],
        "biometric.touchId": [
            "en": "Touch ID",
            "es": "Touch ID",
            "fr": "Touch ID",
            "pt": "Touch ID",
            "ja": "Touch ID",
            "ko": "Touch ID",
        ],
        "biometric.opticId": [
            "en": "Optic ID",
            "es": "Optic ID",
            "fr": "Optic ID",
            "pt": "Optic ID",
            "ja": "Optic ID",
            "ko": "Optic ID",
        ],
        "biometric.biometrics": [
            "en": "Biometrics",
            "es": "Biometr\u{00ED}a",
            "fr": "Biom\u{00E9}trie",
            "pt": "Biometria",
            "ja": "\u{751F}\u{4F53}\u{8A8D}\u{8A3C}",
            "ko": "\u{C0DD}\u{CCB4} \u{C778}\u{C99D}",
        ],
    ]
}
