import Foundation

extension AppStrings {
    static let translationsDebtDetail: [String: [String: String]] = [
        "detail.recordPayment": [
            "en": "Record Payment",
            "es": "Registrar Pago",
            "fr": "Enregistrer Paiement",
            "pt": "Registrar Pagamento",
            "ja": "\u{652F}\u{6255}\u{3044}\u{3092}\u{8A18}\u{9332}",
            "ko": "\u{ACB0}\u{C81C} \u{AE30}\u{B85D}",
        ],
        "detail.paymentHistory": [
            "en": "Payment History",
            "es": "Historial de Pagos",
            "fr": "Historique des Paiements",
            "pt": "Hist\u{00F3}rico de Pagamentos",
            "ja": "\u{652F}\u{6255}\u{3044}\u{5C65}\u{6B74}",
            "ko": "\u{ACB0}\u{C81C} \u{B0B4}\u{C5ED}",
        ],
        "detail.noPayments": [
            "en": "No payments recorded yet.",
            "es": "A\u{00FA}n no hay pagos registrados.",
            "fr": "Aucun paiement enregistr\u{00E9}.",
            "pt": "Nenhum pagamento registrado.",
            "ja": "\u{652F}\u{6255}\u{3044}\u{8A18}\u{9332}\u{306F}\u{3042}\u{308A}\u{307E}\u{305B}\u{3093}\u{3002}",
            "ko": "\u{ACB0}\u{C81C} \u{AE30}\u{B85D}\u{C774} \u{C5C6}\u{C2B5}\u{B2C8}\u{B2E4}.",
        ],
        "detail.forgiveDebt": [
            "en": "Forgive Debt",
            "es": "Perdonar Deuda",
            "fr": "Pardonner la Dette",
            "pt": "Perdoar D\u{00ED}vida",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{514D}\u{9664}",
            "ko": "\u{BE5A} \u{D0D5}\u{AC10}",
        ],
        "detail.deleteDebt": [
            "en": "Delete Debt",
            "es": "Eliminar Deuda",
            "fr": "Supprimer la Dette",
            "pt": "Excluir D\u{00ED}vida",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{524A}\u{9664}",
            "ko": "\u{BE5A} \u{C0AD}\u{C81C}",
        ],
        "detail.paid": [
            "en": "Paid: %@",
            "es": "Pagado: %@",
            "fr": "Pay\u{00E9}: %@",
            "pt": "Pago: %@",
            "ja": "\u{652F}\u{6255}\u{6E08}: %@",
            "ko": "\u{C0C1}\u{D658}\u{C561}: %@",
        ],
        "detail.remaining": [
            "en": "Remaining: %@",
            "es": "Restante: %@",
            "fr": "Restant: %@",
            "pt": "Restante: %@",
            "ja": "\u{6B8B}\u{308A}: %@",
            "ko": "\u{B0A8}\u{C740} \u{AE08}\u{C561}: %@",
        ],
        "detail.created": [
            "en": "Created",
            "es": "Creada",
            "fr": "Cr\u{00E9}\u{00E9}",
            "pt": "Criada",
            "ja": "\u{4F5C}\u{6210}\u{65E5}",
            "ko": "\u{C0DD}\u{C131}\u{C77C}",
        ],
        "detail.dueDate": [
            "en": "Due Date",
            "es": "Fecha de Vencimiento",
            "fr": "Date d'\u{00E9}ch\u{00E9}ance",
            "pt": "Data de Vencimento",
            "ja": "\u{671F}\u{9650}\u{65E5}",
            "ko": "\u{B9CC}\u{AE30}\u{C77C}",
        ],
        "detail.category": [
            "en": "Category",
            "es": "Categor\u{00ED}a",
            "fr": "Cat\u{00E9}gorie",
            "pt": "Categoria",
            "ja": "\u{30AB}\u{30C6}\u{30B4}\u{30EA}",
            "ko": "\u{CE74}\u{D14C}\u{ACE0}\u{B9AC}",
        ],
        "detail.notes": [
            "en": "Notes",
            "es": "Notas",
            "fr": "Notes",
            "pt": "Notas",
            "ja": "\u{30E1}\u{30E2}",
            "ko": "\u{BA54}\u{BAA8}",
        ],
        "addDebt.title": [
            "en": "New Debt",
            "es": "Nueva Deuda",
            "fr": "Nouvelle Dette",
            "pt": "Nova D\u{00ED}vida",
            "ja": "\u{65B0}\u{3057}\u{3044}\u{50B5}\u{52D9}",
            "ko": "\u{C0C8} \u{BE5A}",
        ],
        "addDebt.description": [
            "en": "Description",
            "es": "Descripci\u{00F3}n",
            "fr": "Description",
            "pt": "Descri\u{00E7}\u{00E3}o",
            "ja": "\u{8AAC}\u{660E}",
            "ko": "\u{C124}\u{BA85}",
        ],
        "addDebt.placeholder": [
            "en": "What's this for?",
            "es": "\u{00BF}Para qu\u{00E9} es?",
            "fr": "C'est pour quoi?",
            "pt": "Para que \u{00E9}?",
            "ja": "\u{4F55}\u{306E}\u{305F}\u{3081}\u{3067}\u{3059}\u{304B}\u{FF1F}",
            "ko": "\u{BB34}\u{C5C7} \u{C704}\u{D55C} \u{AC83}\u{C778}\u{AC00}\u{C694}?",
        ],
        "addDebt.person": [
            "en": "Person",
            "es": "Persona",
            "fr": "Personne",
            "pt": "Pessoa",
            "ja": "\u{4EBA}\u{7269}",
            "ko": "\u{C0AC}\u{B78C}",
        ],
        "addDebt.namePlaceholder": [
            "en": "Name",
            "es": "Nombre",
            "fr": "Nom",
            "pt": "Nome",
            "ja": "\u{540D}\u{524D}",
            "ko": "\u{C774}\u{B984}",
        ],
        "addDebt.category": [
            "en": "Category",
            "es": "Categor\u{00ED}a",
            "fr": "Cat\u{00E9}gorie",
            "pt": "Categoria",
            "ja": "\u{30AB}\u{30C6}\u{30B4}\u{30EA}",
            "ko": "\u{CE74}\u{D14C}\u{ACE0}\u{B9AC}",
        ],
        "addDebt.dueDate": [
            "en": "Due Date",
            "es": "Fecha de Vencimiento",
            "fr": "Date d'\u{00E9}ch\u{00E9}ance",
            "pt": "Data de Vencimento",
            "ja": "\u{671F}\u{9650}\u{65E5}",
            "ko": "\u{B9CC}\u{AE30}\u{C77C}",
        ],
        "addDebt.notes": [
            "en": "Notes",
            "es": "Notas",
            "fr": "Notes",
            "pt": "Notas",
            "ja": "\u{30E1}\u{30E2}",
            "ko": "\u{BA54}\u{BAA8}",
        ],
        "addDebt.notesPlaceholder": [
            "en": "Optional notes...",
            "es": "Notas opcionales...",
            "fr": "Notes optionnelles...",
            "pt": "Notas opcionais...",
            "ja": "\u{30E1}\u{30E2}\u{FF08}\u{4EFB}\u{610F}\u{FF09}...",
            "ko": "\u{BA54}\u{BAA8}(\u{C120}\u{D0DD})...",
        ],
        "addDebt.setReminder": [
            "en": "Set Reminder",
            "es": "Establecer Recordatorio",
            "fr": "D\u{00E9}finir un Rappel",
            "pt": "Definir Lembrete",
            "ja": "\u{30EA}\u{30DE}\u{30A4}\u{30F3}\u{30C0}\u{30FC}\u{3092}\u{8A2D}\u{5B9A}",
            "ko": "\u{C54C}\u{B9BC} \u{C124}\u{C815}",
        ],
        "addDebt.addDebt": [
            "en": "Add Debt",
            "es": "Agregar Deuda",
            "fr": "Ajouter une Dette",
            "pt": "Adicionar D\u{00ED}vida",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{8FFD}\u{52A0}",
            "ko": "\u{BE5A} \u{CD94}\u{AC00}",
        ],
        "editDebt.title": [
            "en": "Edit Debt",
            "es": "Editar Deuda",
            "fr": "Modifier la Dette",
            "pt": "Editar D\u{00ED}vida",
            "ja": "\u{50B5}\u{52D9}\u{3092}\u{7DE8}\u{96C6}",
            "ko": "\u{BE5A} \u{D3B8}\u{C9D1}",
        ],
        "payment.title": [
            "en": "Record Payment",
            "es": "Registrar Pago",
            "fr": "Enregistrer Paiement",
            "pt": "Registrar Pagamento",
            "ja": "\u{652F}\u{6255}\u{3044}\u{3092}\u{8A18}\u{9332}",
            "ko": "\u{ACB0}\u{C81C} \u{AE30}\u{B85D}",
        ],
        "payment.remaining": [
            "en": "Remaining: %@",
            "es": "Restante: %@",
            "fr": "Restant: %@",
            "pt": "Restante: %@",
            "ja": "\u{6B8B}\u{308A}: %@",
            "ko": "\u{B0A8}\u{C740} \u{AE08}\u{C561}: %@",
        ],
        "payment.payFullAmount": [
            "en": "Pay Full Amount",
            "es": "Pagar Monto Total",
            "fr": "Payer la Totalit\u{00E9}",
            "pt": "Pagar Valor Total",
            "ja": "\u{5168}\u{984D}\u{652F}\u{6255}\u{3044}",
            "ko": "\u{C804}\u{C561} \u{ACB0}\u{C81C}",
        ],
        "payment.paymentDate": [
            "en": "Payment Date",
            "es": "Fecha de Pago",
            "fr": "Date de Paiement",
            "pt": "Data do Pagamento",
            "ja": "\u{652F}\u{6255}\u{65E5}",
            "ko": "\u{ACB0}\u{C81C}\u{C77C}",
        ],
        "payment.notesPlaceholder": [
            "en": "Notes (optional)",
            "es": "Notas (opcional)",
            "fr": "Notes (optionnel)",
            "pt": "Notas (opcional)",
            "ja": "\u{30E1}\u{30E2}\u{FF08}\u{4EFB}\u{610F}\u{FF09}",
            "ko": "\u{BA54}\u{BAA8}(\u{C120}\u{D0DD})",
        ],
        "payment.paidInFull": [
            "en": "Paid in full",
            "es": "Pagado en su totalidad",
            "fr": "Pay\u{00E9} en totalit\u{00E9}",
            "pt": "Pago integralmente",
            "ja": "\u{5168}\u{984D}\u{652F}\u{6255}\u{3044}\u{6E08}\u{307F}",
            "ko": "\u{C804}\u{C561} \u{C0C1}\u{D658} \u{C644}\u{B8CC}",
        ],
    ]
}
