import Foundation

extension AppStrings {
    static let translationsDashboard: [String: [String: String]] = [
        "dashboard.activeDebts": [
            "en": "Active Debts",
            "es": "Deudas Activas",
            "fr": "Dettes Actives",
            "pt": "D\u{00ED}vidas Ativas",
            "ja": "\u{6D3B}\u{52D5}\u{4E2D}\u{306E}\u{50B5}\u{52D9}",
            "ko": "\u{D65C}\u{C131} \u{BE5A}",
        ],
        "dashboard.overdue": [
            "en": "Overdue",
            "es": "Vencidas",
            "fr": "En Retard",
            "pt": "Atrasadas",
            "ja": "\u{671F}\u{9650}\u{5207}\u{308C}",
            "ko": "\u{C5F0}\u{CCB4}",
        ],
        "dashboard.lifetimeStats": [
            "en": "LIFETIME STATS",
            "es": "ESTAD\u{00CD}STICAS TOTALES",
            "fr": "STATISTIQUES GLOBALES",
            "pt": "ESTAT\u{00CD}STICAS GERAIS",
            "ja": "\u{7D71}\u{8A08}",
            "ko": "\u{C804}\u{CCB4} \u{D1B5}\u{ACC4}",
        ],
        "dashboard.seeAll": [
            "en": "See all",
            "es": "Ver todo",
            "fr": "Tout voir",
            "pt": "Ver tudo",
            "ja": "\u{3059}\u{3079}\u{3066}\u{8868}\u{793A}",
            "ko": "\u{BAA8}\u{B450} \u{BCF4}\u{AE30}",
        ],
        "dashboard.almostPaid": [
            "en": "Almost Paid",
            "es": "Casi Pagadas",
            "fr": "Presque Pay\u{00E9}es",
            "pt": "Quase Pagas",
            "ja": "\u{307B}\u{307C}\u{5B8C}\u{6E08}",
            "ko": "\u{AC70}\u{C758} \u{C644}\u{B0A9}",
        ],
        "dashboard.actionNew": [
            "en": "Add",
            "es": "A\u{00F1}adir",
            "fr": "Ajouter",
            "pt": "Adicionar",
            "ja": "\u{8FFD}\u{52A0}",
            "ko": "\u{CD94}\u{AC00}",
        ],
        "dashboard.actionPay": [
            "en": "Pay",
            "es": "Pagar",
            "fr": "Payer",
            "pt": "Pagar",
            "ja": "\u{652F}\u{6255}\u{3044}",
            "ko": "\u{AC70}\u{C81C}",
        ],
        "dashboard.actionPeople": [
            "en": "People",
            "es": "Gente",
            "fr": "Personnes",
            "pt": "Pessoas",
            "ja": "\u{4EBA}\u{3005}",
            "ko": "\u{C0AC}\u{B78C}\u{B4E4}",
        ],
        "dashboard.actionMore": [
            "en": "More",
            "es": "M\u{00E1}s",
            "fr": "Plus",
            "pt": "Mais",
            "ja": "\u{4ED6}",
            "ko": "\u{B354}\u{BCF4}\u{AE30}",
        ],
        "progress.almostPaidOff": [
            "en": "Almost Paid Off",
            "es": "Casi Pagadas",
            "fr": "Presque Rembours\u{00E9}",
            "pt": "Quase Pagas",
            "ja": "\u{3082}\u{3046}\u{3059}\u{3050}\u{5B8C}\u{6E08}",
            "ko": "\u{AC70}\u{C758} \u{C644}\u{B0A9}",
        ],
        "progress.empty": [
            "en": "No debts with partial payments yet.",
            "es": "A\u{00FA}n no hay deudas con pagos parciales.",
            "fr": "Aucune dette avec paiements partiels.",
            "pt": "Nenhuma d\u{00ED}vida com pagamentos parciais.",
            "ja": "\u{90E8}\u{5206}\u{652F}\u{6255}\u{3044}\u{306E}\u{3042}\u{308B}\u{50B5}\u{52D9}\u{306F}\u{3042}\u{308A}\u{307E}\u{305B}\u{3093}\u{3002}",
            "ko": "\u{BD80}\u{BD84} \u{C0C1}\u{D658}\u{B41C} \u{BE5A}\u{C774} \u{C5C6}\u{C2B5}\u{B2C8}\u{B2E4}.",
        ],
        "recent.title": [
            "en": "Recent Payments",
            "es": "Pagos Recientes",
            "fr": "Paiements R\u{00E9}cents",
            "pt": "Pagamentos Recentes",
            "ja": "\u{6700}\u{8FD1}\u{306E}\u{652F}\u{6255}\u{3044}",
            "ko": "\u{CD5C}\u{ADF8} \u{ACB0}\u{C81C}",
        ],
        "recent.empty": [
            "en": "No payments recorded yet.",
            "es": "A\u{00FA}n no hay pagos registrados.",
            "fr": "Aucun paiement enregistr\u{00E9}.",
            "pt": "Nenhum pagamento registrado.",
            "ja": "\u{652F}\u{6255}\u{3044}\u{8A18}\u{9332}\u{306F}\u{3042}\u{308A}\u{307E}\u{305B}\u{3093}\u{3002}",
            "ko": "\u{ACB0}\u{C81C} \u{AE30}\u{B85D}\u{C774} \u{C5C6}\u{C2B5}\u{B2C8}\u{B2E4}.",
        ],
        "stats.totalDebts": [
            "en": "Total Debts",
            "es": "Total Deudas",
            "fr": "Total Dettes",
            "pt": "Total D\u{00ED}vidas",
            "ja": "\u{50B5}\u{52D9}\u{5408}\u{8A08}",
            "ko": "\u{CD1D} \u{BE5A}",
        ],
        "stats.amountTracked": [
            "en": "Amount Tracked",
            "es": "Monto Rastreado",
            "fr": "Montant Suivi",
            "pt": "Valor Rastreado",
            "ja": "\u{8FFD}\u{8DE1}\u{91D1}\u{984D}",
            "ko": "\u{CD94}\u{C801} \u{AE08}\u{C561}",
        ],
        "stats.paidOff": [
            "en": "Paid Off",
            "es": "Pagadas",
            "fr": "Rembours\u{00E9}",
            "pt": "Pagas",
            "ja": "\u{5B8C}\u{6E08}",
            "ko": "\u{C644}\u{B0A9}",
        ],
        "stats.avgDebt": [
            "en": "Avg. Debt",
            "es": "Deuda Prom.",
            "fr": "Moy. Dette",
            "pt": "M\u{00E9}d. D\u{00ED}vida",
            "ja": "\u{5E73}\u{5747}\u{50B5}\u{52D9}",
            "ko": "\u{D3C9}\u{ADE0} \u{BE5A}",
        ],
        "stats.people": [
            "en": "People",
            "es": "Personas",
            "fr": "Personnes",
            "pt": "Pessoas",
            "ja": "\u{4EBA}\u{6570}",
            "ko": "\u{C0AC}\u{B78C}",
        ],
        "stats.payments": [
            "en": "Payments",
            "es": "Pagos",
            "fr": "Paiements",
            "pt": "Pagamentos",
            "ja": "\u{652F}\u{6255}\u{3044}",
            "ko": "\u{ACB0}\u{C81C}",
        ],
    ]
}
