import Foundation

extension AppStrings {
    static let translationsCommon: [String: [String: String]] = [
        "common.cancel": [
            "en": "Cancel",
            "es": "Cancelar",
            "fr": "Annuler",
            "pt": "Cancelar",
            "ja": "\u{30AD}\u{30E3}\u{30F3}\u{30BB}\u{30EB}",
            "ko": "\u{CE58}\u{C18C}",
        ],
        "common.delete": [
            "en": "Delete",
            "es": "Eliminar",
            "fr": "Supprimer",
            "pt": "Excluir",
            "ja": "\u{524A}\u{9664}",
            "ko": "\u{C0AD}\u{C81C}",
        ],
        "common.done": [
            "en": "Done",
            "es": "Listo",
            "fr": "Termin\u{00E9}",
            "pt": "Conclu\u{00ED}do",
            "ja": "\u{5B8C}\u{4E86}",
            "ko": "\u{C644}\u{B8CC}",
        ],
        "common.ok": [
            "en": "OK",
            "es": "OK",
            "fr": "OK",
            "pt": "OK",
            "ja": "OK",
            "ko": "\u{D655}\u{C778}",
        ],
        "common.unknown": [
            "en": "Unknown",
            "es": "Desconocido",
            "fr": "Inconnu",
            "pt": "Desconhecido",
            "ja": "\u{4E0D}\u{660E}",
            "ko": "\u{C54C} \u{C218} \u{C5C6}\u{C74C}",
        ],
        "common.back": [
            "en": "Back",
            "es": "Atr\u{00E1}s",
            "fr": "Retour",
            "pt": "Voltar",
            "ja": "\u{623B}\u{308B}",
            "ko": "\u{B4A4}\u{B85C}",
        ],
        "common.next": [
            "en": "Next",
            "es": "Siguiente",
            "fr": "Suivant",
            "pt": "Pr\u{00F3}ximo",
            "ja": "\u{6B21}\u{3078}",
            "ko": "\u{B2E4}\u{C74C}",
        ],
        "common.getStarted": [
            "en": "Get Started",
            "es": "Comenzar",
            "fr": "Commencer",
            "pt": "Come\u{00E7}ar",
            "ja": "\u{59CB}\u{3081}\u{308B}",
            "ko": "\u{C2DC}\u{C791}\u{D558}\u{AE30}",
        ],
        "common.markAsPaid": [
            "en": "Mark as Paid",
            "es": "Marcar como Pagada",
            "fr": "Marquer comme Pay\u{00E9}",
            "pt": "Marcar como Paga",
            "ja": "\u{652F}\u{6255}\u{6E08}\u{307F}\u{306B}\u{3059}\u{308B}",
            "ko": "\u{C0C1}\u{D658} \u{C644}\u{B8CC}\u{B85C} \u{D45C}\u{C2DC}",
        ],
        "common.close": [
            "en": "Close",
            "es": "Cerrar",
            "fr": "Fermer",
            "pt": "Fechar",
            "ja": "\u{9589}\u{3058}\u{308B}",
            "ko": "\u{B2EB}\u{AE30}",
        ],
        "common.edit": [
            "en": "Edit",
            "es": "Editar",
            "fr": "Modifier",
            "pt": "Editar",
            "ja": "\u{7DE8}\u{96C6}",
            "ko": "\u{D3B8}\u{C9D1}",
        ],
        "common.copy": [
            "en": "Copy",
            "es": "Copiar",
            "fr": "Copier",
            "pt": "Copiar",
            "ja": "\u{30B3}\u{30D4}\u{30FC}",
            "ko": "\u{BCF5}\u{C0AC}",
        ],
        "common.clear": [
            "en": "Clear",
            "es": "Borrar",
            "fr": "Effacer",
            "pt": "Limpar",
            "ja": "\u{30AF}\u{30EA}\u{30A2}",
            "ko": "\u{C9C0}\u{C6B0}\u{AE30}",
        ],
    ]
}
