import Foundation

extension AppStrings {
    static let translationsAppearance: [String: [String: String]] = [
        "appearance.title": [
            "en": "Appearance",
            "es": "Apariencia",
            "fr": "Apparence",
            "pt": "Apar\u{00EA}ncia",
            "ja": "\u{5916}\u{89B3}",
            "ko": "\u{C678}\u{AD00}",
        ],
        "appearance.currency": [
            "en": "Currency",
            "es": "Moneda",
            "fr": "Devise",
            "pt": "Moeda",
            "ja": "\u{901A}\u{8CA8}",
            "ko": "\u{D1B5}\u{D654}",
        ],
        "appearance.currencyConverter": [
            "en": "Currency Converter",
            "es": "Convertidor de Moneda",
            "fr": "Convertisseur de Devises",
            "pt": "Conversor de Moeda",
            "ja": "\u{901A}\u{8CA8}\u{30B3}\u{30F3}\u{30D0}\u{30FC}\u{30BF}\u{30FC}",
            "ko": "\u{D1B5}\u{D654} \u{BCC0}\u{D658}\u{AE30}",
        ],
        "appearance.amountPlaceholder": [
            "en": "Amount",
            "es": "Monto",
            "fr": "Montant",
            "pt": "Valor",
            "ja": "\u{91D1}\u{984D}",
            "ko": "\u{AE08}\u{C561}",
        ],
        "appearance.ratesError": [
            "en": "Could not load rates",
            "es": "No se pudieron cargar las tasas",
            "fr": "Impossible de charger les taux",
            "pt": "N\u{00E3}o foi poss\u{00ED}vel carregar as taxas",
            "ja": "\u{30EC}\u{30FC}\u{30C8}\u{3092}\u{8AAD}\u{307F}\u{8FBC}\u{3081}\u{307E}\u{305B}\u{3093}\u{3067}\u{3057}\u{305F}",
            "ko": "\u{D658}\u{C728}\u{C744} \u{B85C}\u{B4DC}\u{D560} \u{C218} \u{C5C6}\u{C2B5}\u{B2C8}\u{B2E4}",
        ],
        "appearance.rate.format": [
            "en": "1 USD = %@ %@",
            "es": "1 USD = %@ %@",
            "fr": "1 USD = %@ %@",
            "pt": "1 USD = %@ %@",
            "ja": "1 USD = %@ %@",
            "ko": "1 USD = %@ %@",
        ],
        "appearance.ratesUpdated": [
            "en": "Rates updated %@",
            "es": "Tasas actualizadas %@",
            "fr": "Taux mis \u{00E0} jour %@",
            "pt": "Taxas atualizadas %@",
            "ja": "\u{30EC}\u{30FC}\u{30C8}\u{66F4}\u{65B0}: %@",
            "ko": "\u{D658}\u{C728} \u{C5C5}\u{B370}\u{C774}\u{D2B8}: %@",
        ],
        "appearance.defaultDirection": [
            "en": "Default Direction for New Debts",
            "es": "Direcci\u{00F3}n Predeterminada para Nuevas Deudas",
            "fr": "Direction par D\u{00E9}faut pour les Nouvelles Dettes",
            "pt": "Dire\u{00E7}\u{00E3}o Padr\u{00E3}o para Novas D\u{00ED}vidas",
            "ja": "\u{65B0}\u{3057}\u{3044}\u{50B5}\u{52D9}\u{306E}\u{30C7}\u{30D5}\u{30A9}\u{30EB}\u{30C8}\u{65B9}\u{5411}",
            "ko": "\u{C0C8} \u{BE5A}\u{C758} \u{AE30}\u{BCF8} \u{BC29}\u{D5A5}",
        ],
        "appearance.theme": [
            "en": "Theme",
            "es": "Tema",
            "fr": "Th\u{00E8}me",
            "pt": "Tema",
            "ja": "\u{30C6}\u{30FC}\u{30DE}",
            "ko": "\u{D14C}\u{B9C8}",
        ],
        "theme.midnight": [
            "en": "Midnight Purple",
            "es": "P\u{00FA}rpura Medianoche",
            "fr": "Violet Minuit",
            "pt": "Roxo Meia-Noite",
            "ja": "\u{30DF}\u{30C3}\u{30C9}\u{30CA}\u{30A4}\u{30C8}\u{30D1}\u{30FC}\u{30D7}\u{30EB}",
            "ko": "\u{C790}\u{C815} \u{C790}\u{C8FC}\u{C0C9}",
        ],
        "theme.ocean": [
            "en": "Ocean Deep",
            "es": "Oc\u{00E9}ano Profundo",
            "fr": "Oc\u{00E9}an Profond",
            "pt": "Oceano Profundo",
            "ja": "\u{30C7}\u{30A3}\u{30FC}\u{30D7}\u{30AA}\u{30FC}\u{30B7}\u{30E3}\u{30F3}",
            "ko": "\u{C2EC}\u{D574}",
        ],
        "theme.sunset": [
            "en": "Sunset Ember",
            "es": "Brasa del Atardecer",
            "fr": "Braise de Coucher",
            "pt": "Brasa do P\u{00F4}r-do-Sol",
            "ja": "\u{30B5}\u{30F3}\u{30BB}\u{30C3}\u{30C8}\u{30A8}\u{30F3}\u{30D0}\u{30FC}",
            "ko": "\u{C11D}\u{C591} \u{BD88}\u{AC00}\u{B9AC}",
        ],
        "theme.forest": [
            "en": "Forest Pine",
            "es": "Pino del Bosque",
            "fr": "Pin Forestier",
            "pt": "Pinheiro Florestal",
            "ja": "\u{30D5}\u{30A9}\u{30EC}\u{30B9}\u{30C8}\u{30D1}\u{30A4}\u{30F3}",
            "ko": "\u{C232} \u{C18C}\u{B098}\u{BB34}",
        ],
        "theme.carbon": [
            "en": "Mono Carbon",
            "es": "Carb\u{00F3}n Mono",
            "fr": "Carbone Mono",
            "pt": "Carbono Mono",
            "ja": "\u{30E2}\u{30CE}\u{30AB}\u{30FC}\u{30DC}\u{30F3}",
            "ko": "\u{BAA8}\u{B178} \u{CE74}\u{BCF8}",
        ],
        "theme.porcelain": [
            "en": "Porcelain Light",
            "es": "Porcelana Claro",
            "fr": "Porcelaine Clair",
            "pt": "Porcelana Claro",
            "ja": "\u{30DD}\u{30FC}\u{30BB}\u{30EA}\u{30F3}\u{30E9}\u{30A4}\u{30C8}",
            "ko": "\u{D3EC}\u{C13C}\u{B9B0} \u{B77C}\u{C774}\u{D2B8}",
        ],
        "currency.chooseCurrency": [
            "en": "Choose Your Currency",
            "es": "Elige tu Moneda",
            "fr": "Choisissez Votre Devise",
            "pt": "Escolha Sua Moeda",
            "ja": "\u{901A}\u{8CA8}\u{3092}\u{9078}\u{629E}",
            "ko": "\u{D1B5}\u{D654}\u{B97C} \u{C120}\u{D0DD}\u{D558}\u{C138}\u{C694}",
        ],
        "currency.subtitle": [
            "en": "You can change this later in Settings",
            "es": "Puedes cambiarlo despu\u{00E9}s en Ajustes",
            "fr": "Vous pouvez modifier cela plus tard dans les R\u{00E9}glages",
            "pt": "Voc\u{00EA} pode alterar isso depois em Configura\u{00E7}\u{00F5}es",
            "ja": "\u{5F8C}\u{3067}\u{8A2D}\u{5B9A}\u{3067}\u{5909}\u{66F4}\u{3067}\u{304D}\u{307E}\u{3059}",
            "ko": "\u{B098}\u{C911}\u{C5D0} \u{C124}\u{C815}\u{C5D0}\u{C11C} \u{BCC0}\u{ACBD}\u{D560} \u{C218} \u{C788}\u{C2B5}\u{B2C8}\u{B2E4}",
        ],
        "amount.tapToEnter": [
            "en": "Tap to enter amount",
            "es": "Toca para ingresar monto",
            "fr": "Appuyez pour entrer le montant",
            "pt": "Toque para inserir valor",
            "ja": "\u{30BF}\u{30C3}\u{30D7}\u{3057}\u{3066}\u{91D1}\u{984D}\u{3092}\u{5165}\u{529B}",
            "ko": "\u{D0ED}\u{D558}\u{C5EC} \u{AE08}\u{C561}\u{C744} \u{C785}\u{B825}\u{D558}\u{C138}\u{C694}",
        ],
    ]
}
