import Foundation

extension AppStrings {
    static let translationsTabsAndGreetings: [String: [String: String]] = [
        "tab.dashboard": [
            "en": "Dashboard",
            "es": "Panel",
            "fr": "Tableau de bord",
            "pt": "Painel",
            "ja": "\u{30C0}\u{30C3}\u{30B7}\u{30E5}\u{30DC}\u{30FC}\u{30C9}",
            "ko": "\u{B300}\u{C2DC}\u{BCF4}\u{B4DC}",
        ],
        "tab.debts": [
            "en": "Debts",
            "es": "Deudas",
            "fr": "Dettes",
            "pt": "D\u{00ED}vidas",
            "ja": "\u{50B5}\u{52D9}",
            "ko": "\u{BE5A}",
        ],
        "tab.activity": [
            "en": "Activity",
            "es": "Actividad",
            "fr": "Activit\u{00E9}",
            "pt": "Atividade",
            "ja": "\u{30A2}\u{30AF}\u{30C6}\u{30A3}\u{30D3}\u{30C6}\u{30A3}",
            "ko": "\u{D65C}\u{B3D9}",
        ],
        "tab.settings": [
            "en": "Settings",
            "es": "Ajustes",
            "fr": "R\u{00E9}glages",
            "pt": "Configura\u{00E7}\u{00F5}es",
            "ja": "\u{8A2D}\u{5B9A}",
            "ko": "\u{C124}\u{C815}",
        ],
        "greeting.morning": [
            "en": "Good Morning",
            "es": "Buenos D\u{00ED}as",
            "fr": "Bonjour",
            "pt": "Bom Dia",
            "ja": "\u{304A}\u{306F}\u{3088}\u{3046}\u{3054}\u{3056}\u{3044}\u{307E}\u{3059}",
            "ko": "\u{C88B}\u{C740} \u{C544}\u{CE68}",
        ],
        "greeting.afternoon": [
            "en": "Good Afternoon",
            "es": "Buenas Tardes",
            "fr": "Bon Apr\u{00E8}s-midi",
            "pt": "Boa Tarde",
            "ja": "\u{3053}\u{3093}\u{306B}\u{3061}\u{306F}",
            "ko": "\u{C88B}\u{C740} \u{C624}\u{D6C4}",
        ],
        "greeting.evening": [
            "en": "Good Evening",
            "es": "Buenas Noches",
            "fr": "Bonsoir",
            "pt": "Boa Noite",
            "ja": "\u{3053}\u{3093}\u{3070}\u{3093}\u{306F}",
            "ko": "\u{C88B}\u{C740} \u{C800}\u{B141}",
        ],
        "greeting.subtitle": [
            "en": "Here's your debt overview",
            "es": "Resumen de tus deudas",
            "fr": "Voici votre aper\u{00E7}u des dettes",
            "pt": "Resumo das suas d\u{00ED}vidas",
            "ja": "\u{50B5}\u{52D9}\u{306E}\u{6982}\u{8981}\u{3067}\u{3059}",
            "ko": "\u{BE5A} \u{C694}\u{C57D}\u{C785}\u{B2C8}\u{B2E4}",
        ],
        "balance.netBalance": [
            "en": "Net Balance",
            "es": "Balance Neto",
            "fr": "Solde Net",
            "pt": "Saldo L\u{00ED}quido",
            "ja": "\u{7D14}\u{6B8B}\u{9AD8}",
            "ko": "\u{C21C} \u{C794}\u{C561}",
        ],
        "balance.owedToMe": [
            "en": "Owed to Me",
            "es": "Me Deben",
            "fr": "On Me Doit",
            "pt": "Me Devem",
            "ja": "\u{8CB8}\u{3057}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{BC1B}\u{C744} \u{B3C8}",
        ],
        "balance.iOwe": [
            "en": "I Owe",
            "es": "Yo Debo",
            "fr": "Je Dois",
            "pt": "Eu Devo",
            "ja": "\u{501F}\u{308A}\u{305F}\u{304A}\u{91D1}",
            "ko": "\u{AC1A}\u{C740} \u{B3C8}",
        ],
    ]
}
